data:
  data_dir: ./data/preprocessing
  ckpt_dir: ./ckpt/
  reverse: false
  use_bos: true
  order: null
  punctuation: false
training:
  learning_rate: 5.0e-05
  weight_decay: 0.0
  scheduler_type: linear
  num_warmup_steps: 0
  epochs: 10
  batch_size: 1
  gradient_accumulation_steps: 1
  full_train: false
exp_name: gpt2
debug: false
device: cuda
model_card: gpt2
